# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#站点基础配置
title: Junkor
subTitle: Jun's Tech blog on pages.
name: Junkor
description: 这是 junkor 的一个博客，它是基于 github pages。在这里，主要是一些技术类文章。
url: http://junkor.github.io
feed: /feed.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: github
    url: https://github.com/junkor
    icon: icon-github
    class: none
  - text: links
    url: /links.html
    icon: icon-link
    class: none
#
page:
  - text: objc.io
    url: http://www.objc.io
    last: true
  - text: objccn.io
    url: http://objccn.io
    last: true
  - text: swifter.tips
    url: http://swifter.tips
    last: false

author:
  name: Junkor
