# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: junlinsong@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://junkor.github.io"
twitter_username: junlinsong
github_username:  junkor
facebook_username:  junlinsong

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
